spring:

  kafka:
    bootstrap-servers: localhost:9092

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/appdatabase?authSource=admin

  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5433/hotels_db
    username: postgres
    password: postgres
    hikari:
      schema: app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
      connection-timeout: 10000
server:
  port: 9090

app:
  kafka:
    kafkaBookingTopic: "booking-topic"
    kafkaMessageGroupId: "message-group-id"
    kafkaUserTopic: "user-topic"